networks:
  local_microservice_network:
  loki:

services:

  # Logging system - promtail push to locally deployed grafana: 
  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./src/logger/loki_stack/loki:/etc/loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/loki-dev-config.yml
    networks:
      - loki

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./src/logger/logger_python/logs:/var/log
      - ./src/logger/loki_stack/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-dev-config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./src/logger/loki_stack/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    user: "1000"
    networks:
      - loki

  article_scheduler:
    image: matthewtee/rss_article_scheduler:main
    ports:
      - 80:80
    env_file:
      - .env

  snowflake:
    image: matthewtee/rss_snowflake:main
    ports:
      - "81:8000"
    env_file:
      - .env

  article_ingestor:
    image: matthewtee/rss_article_ingestor:main
    ports:
      - 82:8000
    env_file:
      - .env
    networks:
      - local_microservice_network

  storage_bucket_uploader:
    image: matthewtee/microservice_static_file_ingestor:main
    ports:
      - 83:8000
    env_file:
      - .env
    networks:
      - local_microservice_network

  logger:
    image: matthewtee/microservice_logger:main
    volumes:
      - ./src/logger/logger_python/logs:/logs/
    env_file:
      - .env

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - 9090:9090 
      - 9000:9000
    command: 'server /data --console-address ":9090"'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    networks:
      - local_microservice_network
    volumes:
      - minio_static:/data

volumes:
  minio_static:

