services:
  article_scheduler:
    image: matthewtee/rss_article_scheduler:main
    ports:
      - 80:80
    env_file:
      - .env

  snowflake:
    image: matthewtee/rss_snowflake:main
    ports:
      - 81:80
    env_file:
      - .env
 
  article_ingestor:
    image: matthewtee/rss_article_ingestor:main
    ports:
      - 82:80
    env_file:
      - .env
 
  logger:
    image: matthewtee/microservice_logger:main
    env_file:
      - .env
