name: Publishes the built Django image to Dockerhub

on:
  push:
    branches: [ main ]

jobs:
  publish_fp_parser:
    name: Push microservice docker containers to the registry
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - dockerfile: ./src/article_ingestor/Dockerfile.python 
            image: matthewtee/rss_article_ingestor
            tags: latest, python-3.11
          - dockerfile: ./src/article_scheduler/
            image: matthewtee/rss_article_scheduler
            tags: latest, python-3.11
          - dockerfile: ./src/snowflake/Dockerfile.python
            image: matthewtee/rss_snowflake
            tags: latest, python-3.11
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
